### ISSUE TITLE
Service call to monarch metric should include all phenotypes

### ISSUE THREAD

**Issue by mellybelly** [phenotips/phenotips#1130]
I think that currently the 5 star metric is now only using the clinical symptoms portion of the record and not the entirety of the Phenotips record. This should probably be the latter. This is also related to #961, basically you can't see anywhere in Phenotips all of the phentoypes that are being saved - but I believe it is this that the metric should be measured against.

**Comment by buske** [comment]
@danielpgross, can you double-check that this is resolved in your implementation of the specificity widget?

**Comment by danielpgross** [comment]
@buske This isn't resolved yet - as of now my implementation falls short of the Monarch endpoint's scoring algorithm, which does some basic calculations on the data returned by owltools before returning the score. I'd like to go over this behaviour with you before I move forward with the implementation, so please let me know when you have a chance, thanks!

**Comment by danielpgross** [comment]
This was fixed in commit 43a01be9965e6e7adbba1e611426082515dd81cc, but not yet merged into master.
